Completed the documentation for Gaussian Mixture Model
Algo-Phantoms/Algo-ScriptML pull request #162
Opened 2021-04-17 14:02 UTC by vinc3nati

I have completed the documentation of Gaussian Mixture Model for issue #142 .

2021-04-28 20:26 UTC, geekquad commented on Gaussian Mixture Model/README.md
> +2. [Scikit Learn](hhttp://scikit-learn.org/stable/modules/mixture.html#:~:text=A%20Gaussian%20mixture%20model%20is,Gaussian%20distributions%20with%20unknown%20parameters.)
Link not working. 
Please make the necessary changes.
![image](https://user-images.githubusercontent.com/47635806/116468153-2389fc00-a88e-11eb-8368-04ca52ba895d.png)

2021-04-28 20:27 UTC, geekquad requested changes
Please make the necessary changes.

2021-04-29 04:06 UTC, vinc3nati commented
> Please make the necessary changes.

Roger that

2021-04-29 07:00 UTC, vinc3nati commented
Done sir @geekquad

2021-04-30 20:11 UTC, geekquad approved these changes
Amazing work @vinc3nati.

2021-04-30 20:12 UTC, merged